In [1]:
import numpy

matrix1=numpy.matrix([[1,2,3],[1,1,1],[1,1,1]])
matrix2=numpy.matrix([[1,0,0],[0,1,0],[0,0,1]])
print("Matrix 1=\n",matrix1)
print("Matrix 2=\n",matrix2)

matrix3=numpy.add(matrix1,matrix2)
matrix4=numpy.subtract(matrix1,matrix2)
matrix5=numpy.matmul(matrix1,matrix2)
matrix6=numpy.transpose(matrix1)

print("Matrix 1 + Matrix 2=\n", matrix3)
print("Matrix 1 - Matrix 2=\n", matrix4)
print("Matrix 1 * Matrix 2=\n", matrix5)
print("2 * Matrix 1=\n", 2*matrix1)
print("Transpose of Matrix 1=\n", matrix6)

Matrix 1=
 [[1 2 3]
 [1 1 1]
 [1 1 1]]
Matrix 2=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
Matrix 1 + Matrix 2=
 [[2 2 3]
 [1 2 1]
 [1 1 2]]
Matrix 1 - Matrix 2=
 [[0 2 3]
 [1 0 1]
 [1 1 0]]
Matrix 1 * Matrix 2=
 [[1 2 3]
 [1 1 1]
 [1 1 1]]
2 * Matrix 1=
 [[2 4 6]
 [2 2 2]
 [2 2 2]]
Transpose of Matrix 1=
 [[1 1 1]
 [2 1 1]
 [3 1 1]]
