In [4]:
import numpy as np

def translationMatrix(tx=0, ty=0, tz=0):
    return np.matrix([[1, 0, 0, tx],
                      [0, 1, 0, ty],
                      [0, 0, 1, tz],
                      [0, 0, 0, 1]])

def rotationMatrixX(degree):
    theta = np.radians(degree)
    c, s = np.cos(theta), np.sin(theta)
    return np.matrix([[1, 0, 0, 0],
                      [0, c, -s, 0],
                      [0, s, c, 0],
                      [0, 0, 0, 1]])

def rotationMatrixY(degree):
    theta = np.radians(degree)
    c, s = np.cos(theta), np.sin(theta)
    return np.matrix([[c, 0, s, 0],
                      [0, 1, 0, 0],
                      [-s, 0, c, 0],
                      [0, 0, 0, 1]])

def rotationMatrixZ(degree):
    theta = np.radians(degree)
    c, s = np.cos(theta), np.sin(theta)
    return np.matrix([[c, -s, 0, 0],
                      [s, c, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])

# Test all matrices
print("Translation Matrix:\n", translationMatrix(1, 1, 1), "\n")
print("Rotation Matrix about X axis:\n", rotationMatrixX(30), "\n")
print("Rotation Matrix about Y axis:\n", rotationMatrixY(30), "\n")
print("Rotation Matrix about Z axis:\n", rotationMatrixZ(30), "\n")


Translation Matrix:
 [[1 0 0 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 1]] 

Rotation Matrix about X axis:
 [[ 1.         0.         0.         0.       ]
 [ 0.         0.8660254 -0.5        0.       ]
 [ 0.         0.5        0.8660254  0.       ]
 [ 0.         0.         0.         1.       ]] 

Rotation Matrix about Y axis:
 [[ 0.8660254  0.         0.5        0.       ]
 [ 0.         1.         0.         0.       ]
 [-0.5        0.         0.8660254  0.       ]
 [ 0.         0.         0.         1.       ]] 

Rotation Matrix about Z axis:
 [[ 0.8660254 -0.5        0.         0.       ]
 [ 0.5        0.8660254  0.         0.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]] 

