In [5]:
from numpy import matrix
from numpy import matmul
from numpy import diag
from scipy.linalg import svd

A=matrix([[1,2,3],
          [4,5,6],
          [7,8,8]])
print (A)
print()
U, S, V = svd(A)
print(U)
print()
print(S)
print()
print(V)
print()

Sigma = diag(S)
print(Sigma)
print()
B =  matmul(U,matmul(Sigma,V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 8]]

[[-0.2199626  -0.77804471 -0.58844106]
 [-0.53678521 -0.40714295  0.73898326]
 [-0.81454164  0.47841514 -0.32808667]]

[16.31368816  1.35840058  0.13537586]

[[-0.49460888 -0.59092612 -0.63731341]
 [ 0.69367571  0.17337814 -0.69910946]
 [ 0.52361825 -0.78787457  0.32415673]]

[[16.31368816  0.          0.        ]
 [ 0.          1.35840058  0.        ]
 [ 0.          0.          0.13537586]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 8.]]
