In [5]:
from matplotlib import pyplot
from numpy import array

fig,ax = pyplot.subplots(1,1)
a = array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27])
ax.hist(a, bins = [0,10,20,30,40,60,70,80,90,100])
ax.set_title("histogram pf result")
ax.set_xticks([0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
ax.set_xlabel('marks')
ax.set_ylabel('no of students')
pyplot.show()

[[1 2 3]
 [4 5 6]
 [7 8 8]]

[[-0.2199626  -0.77804471 -0.58844106]
 [-0.53678521 -0.40714295  0.73898326]
 [-0.81454164  0.47841514 -0.32808667]]

[16.31368816  1.35840058  0.13537586]

[[-0.49460888 -0.59092612 -0.63731341]
 [ 0.69367571  0.17337814 -0.69910946]
 [ 0.52361825 -0.78787457  0.32415673]]

[[16.31368816  0.          0.        ]
 [ 0.          1.35840058  0.        ]
 [ 0.          0.          0.13537586]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 8.]]
